import { createApp } from "vue";
import App from "./App.vue";
import { Icon } from "@iconify/vue";
import router from "./router";
import Antd from "ant-design-vue";
import store from "./store";
import "./style.css";
const app = createApp(App).use(router);
app.config.productionTip = false;
app.component("Icon", Icon);
app.use(Antd);
app.use(store);
app.mount("#app");
